#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Openwrt Packit

on:
  repository_dispatch:
    types: [Openwrt_Packit]
  workflow_dispatch:
    #  schedule:
    #    - cron: 11 22 * * 5
    inputs:
      openwrt_soc:
        description: 'PACKAGE_SOC for packit action, default value is s905d(N1) & qemu'
        required: false
        default: 's905d'
        type: choice
        options: 
          - s905d
          - vplus
          - cm3
          - jp-tvbox
          - beikeyun
          - l1pro
          - rock5b
          - rock5c
          - e52c
          - e54c
          - r66s
          - r68s
          - h88k
          - h88k-v3
          - ak88
          - ht2
          - e20c
          - h28k
          - h66k
          - h68k
          - h69k
          - h69k-max
          - e25
          - photonicat
          - watermelon-pi
          - zcube1-max
          - rk3399
          - s905
          - s905x2
          - s905x3
          - s912
          - s922x
          - s922x-n2
          - qemu
          - diy
          - all
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "6.6.y_6.12.y"
        type: choice
        options:
          - 6.6.y_6.12.y
          - 5.4.y
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.12.y
          - 5.4.y_5.10.y
          - 5.15.y_6.1.y
          - 6.1.y_6.12.y
          - 6.1.y_6.6.y

jobs:
  packit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Setup Env (on repository_dispatch)
      if:  github.event_name == 'repository_dispatch'
      run: |
        echo "PACKAGE_SOC=s905d" >> "$GITHUB_ENV"
        echo "KERNEL_VERSION_NAME=6.6.y_6.12.y" >> "$GITHUB_ENV"
    
    - name: Setup Env (on workflow_dispatch)
      if:  github.event_name == 'workflow_dispatch'
      run: |
        echo "PACKAGE_SOC=${{ github.event.inputs.openwrt_soc }}" >> "$GITHUB_ENV"
        echo "KERNEL_VERSION_NAME=${{ github.event.inputs.openwrt_kernel }}" >> "$GITHUB_ENV"
    
    - name: Package OpenWrt Firmware
      uses: ophub/flippy-openwrt-actions@main
      env:
          OPENWRT_ARMVIRT: https://github.com/xlighting2017/Actions/releases/download/Immortalwrt_armsr/immortalwrt-armsr-armv8-rootfs.tar.gz
          PACKAGE_SOC: "${{ env.PACKAGE_SOC }}"
          KERNEL_VERSION_NAME: "${{ env.KERNEL_VERSION_NAME }}"
  
    - name: Upload packaged firmware to release
      uses: softprops/action-gh-release@master
      if:  env.PACKAGED_STATUS == 'success' && !cancelled()
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: immortalwrt_${{ env.PACKAGE_SOC }}_${{ env.PACKAGED_OUTPUTDATE }}
          body: |
            Device(s): ${{ env.PACKAGE_SOC }}
            Default IP: 192.168.199.253
            Default password: NULL
            Luci App installed:
              - amlogic
              - frpc
              - mosdns
              - openclash
              - ttyd
              - vlmcsd(KMS)
          files: ${{ env.PACKAGED_OUTPUTPATH }}/*

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        delete_workflow_pattern: ${{ env.PACKAGE_SOC }}
        retain_days: 7
        keep_minimum_runs: 2

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@master
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3
        delete_tags: true
        delete_tag_pattern: ${{ env.PACKAGE_SOC }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
