#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Update Checker

on:
  workflow_dispatch:
  schedule:
    - cron: 11 17 * * 5

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # max-parallel: 3
      matrix:
        REPO_NAME: [immortalwrt,VIKINGYFY]
        REPO_PROJECT: [immortalwrt]
        include:
          - REPO_NAME: qosmio
            REPO_PROJECT: openwrt-ipq
    steps:
    - name: Get Commit Hash
      id: getHash
      run: |
        # decide REPO_BRANCH based on REPO_NAME
        case ${{ matrix.REPO_NAME }} in
          "immortalwrt")
            REPO_BRANCH="master"
            ;;
          "VIKINGYFY")
            REPO_BRANCH="main"
            ;;
          "qosmio")
            REPO_BRANCH="main-nss"
            ;;
          *)
            echo "WRONG/UNKNOWN REPO_NAME ${{ matrix.REPO_NAME }}."
            exit 1
            ;;
        esac
        git clone --depth 1 https://github.com/${{ matrix.REPO_NAME }}/${{ matrix.REPO_PROJECT }} -b $REPO_BRANCH .
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v3
      with:
        path: .commitHash.${{ matrix.REPO_NAME }}
        key: commitHash_${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash.${{ matrix.REPO_NAME }}

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: "Source_Code_Update_${{ matrix.REPO_NAME }}"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 2
        delete_workflow_pattern: "Update Checker"
